package io.homeassistant.companion.android.dashboard.ui

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import io.homeassistant.companion.android.dashboard.data.DashboardConfigResult
import io.homeassistant.companion.android.dashboard.data.DashboardRepository
import io.homeassistant.companion.android.dashboard.entity.EntityStates
import io.homeassistant.companion.android.dashboard.entity.HassConfig
import io.homeassistant.companion.android.dashboard.entity.HassSnapshot
import io.homeassistant.companion.android.dashboard.entity.JsonTranslations
import io.homeassistant.companion.android.dashboard.entity.Localize
import io.homeassistant.companion.android.dashboard.layout.CardGroup
import io.homeassistant.companion.android.dashboard.layout.cardGroups
import io.homeassistant.companion.android.dashboard.model.DashboardConfig
import io.homeassistant.companion.android.dashboard.model.DashboardInfo
import io.homeassistant.companion.android.dashboard.model.string
import io.homeassistant.companion.android.dashboard.strategy.home.HomeDashboardConfig
import io.homeassistant.companion.android.dashboard.strategy.home.homeDashboard
import io.homeassistant.companion.android.dashboard.strategy.resolveStrategyView
import javax.inject.Inject
import kotlin.time.Duration.Companion.seconds
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.filterNotNull
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.flow.shareIn
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.take
import kotlinx.serialization.json.JsonObject

/** What the dashboard screen shows. */
sealed interface DashboardUiState {
    data object Loading : DashboardUiState

    /** The dashboard has no stored config and no ported strategy generates one. */
    data object NotFound : DashboardUiState

    /** The dashboard is generated by a strategy that is not ported yet. */
    data class UnsupportedStrategy(val type: String?) : DashboardUiState

    data class Error(val message: String?) : DashboardUiState

    /**
     * @property groups the selected view's cards, or `null` when that view's strategy is not ported yet
     */
    data class Content(
        val title: String?,
        val viewTitles: List<String?>,
        val selectedView: Int,
        val groups: List<CardGroup>?,
    ) : DashboardUiState
}

/**
 * Raw state: the selected dashboard and view, the stored config, the registries and server details, and the
 * entity states. The dashboard structure (including generated dashboards) is derived from these, and entity
 * states are exposed separately so each card derives only what it shows.
 */
@OptIn(ExperimentalCoroutinesApi::class)
@HiltViewModel
class DashboardViewModel @Inject constructor(private val repository: DashboardRepository) : ViewModel() {

    /** `null` is the default dashboard. */
    private val selectedDashboard = MutableStateFlow<String?>(null)
    private val selectedView = MutableStateFlow(0)

    val dashboards: StateFlow<List<DashboardInfo>> = flow { emit(repository.dashboards()) }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), emptyList())

    val selectedDashboardUrlPath: StateFlow<String?> = selectedDashboard

    /** `null` until the first snapshot of all states has arrived. */
    private val loadedEntityStates: StateFlow<EntityStates?> = repository.entityStates()
        .flowOn(Dispatchers.Default)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), null)

    val entityStates: StateFlow<EntityStates?> = loadedEntityStates

    private val localize: Localize = JsonTranslations.bundled() ?: Localize { "" }

    /**
     * The data the dashboard structure is derived from. Like upstream, structure is regenerated when registries
     * change, not on state changes, so the states are those at the time of the registry update.
     */
    private val structureSnapshot: Flow<StructureInputs> = combine(
        repository.registries(),
        flow { emit(repository.serverInfo()) },
        flow { emit(repository.homeSystemData()) },
        loadedEntityStates.filterNotNull().take(1),
    ) { registries, serverInfo, homeSettings, states ->
        StructureInputs(
            hass = HassSnapshot(
                states = states,
                registries = registries,
                user = serverInfo?.user,
                config = serverInfo?.config ?: HassConfig.UNKNOWN,
                panels = serverInfo?.panels.orEmpty(),
                localize = localize,
            ),
            homeSettings = homeSettings,
        )
    }.shareIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), replay = 1)

    val uiState: StateFlow<DashboardUiState> = selectedDashboard
        .flatMapLatest { urlPath ->
            repository.dashboardConfig(urlPath).combine(structureSnapshot) { result, inputs ->
                Triple(urlPath, result, inputs)
            }
        }
        .combine(selectedView) { (urlPath, result, inputs), viewIndex -> result.toUiState(urlPath, inputs, viewIndex) }
        .flowOn(Dispatchers.Default)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), DashboardUiState.Loading)

    fun onSelectDashboard(urlPath: String?) {
        selectedView.value = 0
        selectedDashboard.value = urlPath
    }

    fun onSelectView(index: Int) {
        selectedView.value = index
    }
}

private data class StructureInputs(val hass: HassSnapshot, val homeSettings: JsonObject?)

private fun DashboardConfigResult.toUiState(
    urlPath: String?,
    inputs: StructureInputs,
    viewIndex: Int,
): DashboardUiState = when (this) {
    is DashboardConfigResult.Error -> DashboardUiState.Error(message)
    // Without a stored default dashboard the frontend shows the generated home dashboard (/home)
    DashboardConfigResult.NotFound -> if (urlPath == null) {
        DashboardConfig(inputs.hass.homeDashboard(HomeDashboardConfig.fromSystemData(inputs.homeSettings)))
            .toContent(inputs.hass, viewIndex)
    } else {
        DashboardUiState.NotFound
    }
    is DashboardConfigResult.Loaded -> config.toContent(inputs.hass, viewIndex)
}

private fun DashboardConfig.toContent(hass: HassSnapshot, viewIndex: Int): DashboardUiState {
    if (isStrategy) return DashboardUiState.UnsupportedStrategy(strategy?.string("type"))
    // A config change can remove views, so clamp instead of keeping a stale index
    val index = viewIndex.coerceIn(0, (views.size - 1).coerceAtLeast(0))
    return DashboardUiState.Content(
        title = title,
        viewTitles = views.map { it.title ?: it.path },
        selectedView = index,
        groups = views.getOrNull(index)?.let { hass.resolveStrategyView(it) }?.let(::cardGroups)
            ?: if (views.isEmpty()) emptyList() else null,
    )
}

private val STOP_TIMEOUT = 5.seconds.inWholeMilliseconds
