package io.homeassistant.companion.android.dashboard.ui

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import dagger.hilt.android.lifecycle.HiltViewModel
import io.homeassistant.companion.android.dashboard.action.CardAction
import io.homeassistant.companion.android.dashboard.action.Gesture
import io.homeassistant.companion.android.dashboard.action.resolveAction
import io.homeassistant.companion.android.dashboard.data.DashboardConfigResult
import io.homeassistant.companion.android.dashboard.data.DashboardRepository
import io.homeassistant.companion.android.dashboard.derive.TemplateRequest
import io.homeassistant.companion.android.dashboard.derive.TemplateResult
import io.homeassistant.companion.android.dashboard.derive.cameraSnapshotEntities
import io.homeassistant.companion.android.dashboard.derive.templateRequests
import io.homeassistant.companion.android.dashboard.display.JdkDisplayFormats
import io.homeassistant.companion.android.dashboard.entity.HassConfig
import io.homeassistant.companion.android.dashboard.entity.HassSnapshot
import io.homeassistant.companion.android.dashboard.entity.IconResources
import io.homeassistant.companion.android.dashboard.entity.JsonTranslations
import io.homeassistant.companion.android.dashboard.entity.Localize
import io.homeassistant.companion.android.dashboard.entity.withFallback
import io.homeassistant.companion.android.dashboard.layout.CardGroup
import io.homeassistant.companion.android.dashboard.layout.cardGroups
import io.homeassistant.companion.android.dashboard.layout.viewHeaderCard
import io.homeassistant.companion.android.dashboard.layout.withNestedCards
import io.homeassistant.companion.android.dashboard.model.DashboardConfig
import io.homeassistant.companion.android.dashboard.model.DashboardInfo
import io.homeassistant.companion.android.dashboard.model.ViewConfig
import io.homeassistant.companion.android.dashboard.model.number
import io.homeassistant.companion.android.dashboard.model.string
import io.homeassistant.companion.android.dashboard.strategy.StrategyData
import io.homeassistant.companion.android.dashboard.strategy.expandView
import io.homeassistant.companion.android.dashboard.strategy.home.HomeDashboardConfig
import io.homeassistant.companion.android.dashboard.strategy.home.homeDashboard
import java.time.ZoneId
import java.time.ZonedDateTime
import java.util.Locale
import javax.inject.Inject
import kotlin.time.Clock
import kotlin.time.Duration.Companion.seconds
import kotlin.time.toJavaInstant
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.ExperimentalCoroutinesApi
import kotlinx.coroutines.channels.Channel
import kotlinx.coroutines.delay
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.SharingStarted
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.flow.distinctUntilChanged
import kotlinx.coroutines.flow.filterNotNull
import kotlinx.coroutines.flow.flatMapLatest
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOf
import kotlinx.coroutines.flow.flowOn
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.onStart
import kotlinx.coroutines.flow.receiveAsFlow
import kotlinx.coroutines.flow.shareIn
import kotlinx.coroutines.flow.stateIn
import kotlinx.coroutines.flow.take
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

/** What the dashboard screen shows. */
sealed interface DashboardUiState {
    data object Loading : DashboardUiState

    /** The dashboard has no stored config and no ported strategy generates one. */
    data object NotFound : DashboardUiState

    /** The dashboard is generated by a strategy that is not ported yet. */
    data class UnsupportedStrategy(val type: String?) : DashboardUiState

    data class Error(val message: String?) : DashboardUiState

    /**
     * @property tabs the top-level views; subviews are only reached through navigation, as upstream
     * @property selectedTab index in [tabs] of the shown view or of the view a subview was opened from
     * @property isSubview whether the shown view is a subview, which shows a back button instead of tabs
     * @property groups the shown view's cards, or `null` when its strategy is not ported yet
     * @property view the shown view with its strategies expanded, for its header and badges
     */
    data class Content(
        val title: String?,
        val tabs: List<ViewTab>,
        val selectedTab: Int,
        val isSubview: Boolean,
        val subviewTitle: String?,
        val viewPath: String,
        /** The view's `max_columns`, bounding the column count `view_columns` conditions see. */
        val maxColumns: Int?,
        val groups: List<CardGroup>?,
        val view: ViewConfig? = null,
    ) : DashboardUiState
}

/** A top-level view, selected by [path] (or its index when it has none). */
data class ViewTab(val title: String?, val icon: String?, val path: String)

/**
 * Raw state: the selected dashboard, the stack of opened view paths, the stored config, the registries and server
 * details, and the entity states. The dashboard structure (including generated dashboards) is derived from these.
 */
@OptIn(ExperimentalCoroutinesApi::class)
@HiltViewModel
class DashboardViewModel @Inject constructor(private val repository: DashboardRepository, private val clock: Clock) :
    ViewModel() {

    /** `null` is the default dashboard. */
    private val selectedDashboard = MutableStateFlow<String?>(null)

    /** Opened views, last is shown. Empty shows the first view. */
    private val viewStack = MutableStateFlow<List<String>>(emptyList())

    /** The current time for `time` conditions, updated often enough for their minute resolution. */
    val now: StateFlow<ZonedDateTime?> = flow {
        while (true) {
            // The frontend's default time zone setting follows the device
            emit(clock.now().toJavaInstant().atZone(ZoneId.systemDefault()))
            delay(CLOCK_TICK)
        }
    }.stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), null)

    val dashboards: StateFlow<List<DashboardInfo>> = flow { emit(repository.dashboards()) }
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), emptyList())

    val selectedDashboardUrlPath: StateFlow<String?> = selectedDashboard

    private val entityStates = repository.entityStates()
        .flowOn(Dispatchers.Default)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), null)

    // Reading the bundled resource touches disk, so never on the main thread
    private val bundledLocalize: Flow<Localize> = flow { emit(JsonTranslations.bundled() ?: Localize { "" }) }
        .flowOn(Dispatchers.IO)

    /** Frontend strings plus the server's entity translations, and the icon translations. */
    private val entityDisplay: Flow<Pair<Localize, IconResources>> = combine(
        bundledLocalize,
        flow { emit(repository.entityResources(BUNDLED_LANGUAGE)) },
    ) { bundled, resources -> bundled.withFallback(resources.translations) to resources.icons }

    /**
     * The data the dashboard structure is derived from. Like upstream, structure is regenerated when registries
     * change, not on state changes, so the states are those at the time of the registry update.
     */
    private val structureInputs: Flow<StructureInputs> = combine(
        repository.registries(),
        flow {
            val serverInfo = repository.serverInfo()
            emit(serverInfo to repository.strategyData(serverInfo?.config?.components.orEmpty()))
        },
        flow { emit(repository.homeSystemData()) },
        entityStates.filterNotNull().take(1),
        entityDisplay,
    ) { registries, (serverInfo, strategyData), homeSettings, states, (localize, icons) ->
        StructureInputs(
            hass = HassSnapshot(
                states = states,
                registries = registries,
                user = serverInfo?.user,
                config = serverInfo?.config ?: HassConfig.UNKNOWN,
                panels = serverInfo?.panels.orEmpty(),
                localize = localize,
                icons = icons,
                formats = JdkDisplayFormats(Locale.forLanguageTag(BUNDLED_LANGUAGE), ZoneId.systemDefault()),
            ),
            strategyData = strategyData,
            homeSettings = homeSettings,
        )
    }.shareIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), replay = 1)

    // Live collections some cards show; `null` until first loaded
    private val repairsIssues = repository.repairsIssues()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), null)
    private val discoveredFlows = repository.discoveredFlows()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), null)

    val uiState: StateFlow<DashboardUiState> = selectedDashboard
        .flatMapLatest { urlPath ->
            repository.dashboardConfig(urlPath).combine(structureInputs) { result, inputs ->
                Triple(urlPath, result, inputs)
            }
        }
        .combine(viewStack) { (urlPath, result, inputs), stack -> result.toUiState(urlPath, inputs, stack) }
        .flowOn(Dispatchers.Default)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), DashboardUiState.Loading)

    /**
     * The renderings of the templates the shown view's cards use, by request. Re-subscribed when the view or its
     * requests change, as each card would.
     */
    private val templates: Flow<Map<TemplateRequest, TemplateResult>> = uiState
        .combine(structureInputs) { state, inputs ->
            val content = state as? DashboardUiState.Content
            val cards =
                withNestedCards(content?.groups?.flatMap { it.cards }.orEmpty()) +
                    listOfNotNull(content?.view?.let(::viewHeaderCard))
            inputs.hass.templateRequests(cards)
        }
        .distinctUntilChanged()
        .flatMapLatest { requests ->
            if (requests.isEmpty()) {
                flowOf(emptyMap())
            } else {
                combine(requests.map { request -> repository.renderTemplate(request).map { request to it } }) {
                    it.toMap()
                }.onStart { emit(emptyMap()) }
            }
        }

    /** Signed snapshot paths of the cameras the shown view's cards show, refreshed like the frontend's `hui-image`. */
    private val cameraImages: Flow<Map<String, String>> = uiState
        .combine(structureInputs) { state, inputs ->
            val content = state as? DashboardUiState.Content
            inputs.hass.cameraSnapshotEntities(withNestedCards(content?.groups?.flatMap { it.cards }.orEmpty()))
        }
        .distinctUntilChanged()
        .flatMapLatest { cameras ->
            if (cameras.isEmpty()) {
                flowOf(emptyMap())
            } else {
                flow {
                    while (true) {
                        emit(
                            cameras.mapNotNull { camera ->
                                repository.cameraSnapshotPath(camera)?.let { camera to it }
                            }.toMap(),
                        )
                        delay(CAMERA_REFRESH)
                    }
                }
            }
        }
        .onStart { emit(emptyMap()) }

    /** The URL server paths (pictures, snapshots) are loaded from. */
    val serverUrl: StateFlow<String?> = repository.serverUrl()
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), null)

    /** The latest snapshot for cards: structure inputs with live entity states and collections. */
    val hass: StateFlow<HassSnapshot?> = combine(
        structureInputs,
        entityStates.filterNotNull(),
        repairsIssues,
        discoveredFlows,
        combine(templates, cameraImages, ::Pair),
    ) { inputs, states, repairs, flows, (rendered, cameras) ->
        inputs.hass.copy(
            states = states,
            repairsIssues = repairs,
            discoveredFlows = flows,
            templates = rendered,
            cameraImages = cameras,
        )
    }.flowOn(Dispatchers.Default)
        .stateIn(viewModelScope, SharingStarted.WhileSubscribed(STOP_TIMEOUT), null)

    fun onSelectDashboard(urlPath: String?) {
        viewStack.value = emptyList()
        selectedDashboard.value = urlPath
    }

    fun onSelectTab(path: String) {
        viewStack.value = listOf(path)
    }

    /**
     * Follow a `navigate` action. Paths without a leading slash are views of the current dashboard, as in the
     * frontend; other panels are not available natively yet and are ignored.
     */
    fun onNavigate(navigationPath: String) {
        if (navigationPath.startsWith("/")) return
        val path = navigationPath.substringBefore('?')
        viewStack.update { it + path }
    }

    private val _events = Channel<DashboardEvent>(Channel.BUFFERED)

    /** One-off effects for the screen: messages, confirmations, links to open. */
    val events: Flow<DashboardEvent> = _events.receiveAsFlow()

    /**
     * Handle [gesture] on a card element configured by [config] (see `cardActions`): resolve it against the
     * current state and run it, after asking for confirmation when the action wants it.
     */
    fun onGesture(config: JsonObject, gesture: Gesture) {
        val snapshot = hass.value ?: return
        viewModelScope.launch {
            val resolved = withContext(Dispatchers.Default) { snapshot.resolveAction(config, gesture) } ?: return@launch
            val confirmation = resolved.confirmation
            if (confirmation != null) {
                _events.send(DashboardEvent.Confirm(confirmation, resolved.action))
            } else {
                run(resolved.action)
            }
        }
    }

    /** Run [action] that a card control started directly, such as a tile feature. */
    fun onAction(action: CardAction) {
        viewModelScope.launch { run(action) }
    }

    /** Run [action] with the [code] the user entered for it. */
    fun onCodeEntered(action: CardAction.CallService, code: String) {
        viewModelScope.launch { callService(action.withCode(code)) }
    }

    /** Run [action] once the user confirmed it. */
    fun onConfirmed(action: CardAction) {
        viewModelScope.launch { run(action) }
    }

    private suspend fun run(action: CardAction) {
        when (action) {
            is CardAction.Navigate -> if (action.path.startsWith("/")) {
                _events.send(DashboardEvent.UnsupportedNavigation(action.path))
            } else {
                onNavigate(action.path)
            }
            is CardAction.CallService -> callProtectedService(action)
            is CardAction.MoreInfo -> _events.send(DashboardEvent.MoreInfo(action.entityId))
            is CardAction.OpenUrl -> _events.send(DashboardEvent.OpenUrl(action.url))
            is CardAction.Failure -> _events.send(DashboardEvent.Message(action.message))
            is CardAction.Assist -> _events.send(DashboardEvent.UnsupportedAction(ACTION_ASSIST))
            is CardAction.FireDomEvent -> _events.send(DashboardEvent.UnsupportedAction(ACTION_FIRE_DOM_EVENT))
        }
    }

    /** A service that may need a code: use the entity's default code, or ask the user, as upstream does. */
    private suspend fun callProtectedService(call: CardAction.CallService) {
        val code = call.code ?: return callService(call)
        if (repository.defaultCode(code.entityId, code.optionsDomain) != null) {
            // The server applies the default code itself
            callService(call)
        } else {
            _events.send(DashboardEvent.EnterCode(call))
        }
    }

    private suspend fun callService(call: CardAction.CallService) {
        val error = repository.callService(call.domain, call.service, call.data, call.target) ?: return
        // Like upstream's notifyOnError toast: "Failed to perform the action light/turn_on. <message>"
        val localize = hass.value?.localize ?: return
        val failed = localize(
            "ui.notification_toast.action_failed",
            mapOf("service" to "${call.domain}/${call.service}"),
        )
        _events.send(DashboardEvent.Message(listOf(failed, error).filter(String::isNotEmpty).joinToString(" ")))
    }

    /** @return whether a view was closed; the first view is implicit, so an empty stack shows it */
    fun onBack(): Boolean {
        if (viewStack.value.isEmpty()) return false
        viewStack.update { it.dropLast(1) }
        return true
    }
}

private data class StructureInputs(
    val hass: HassSnapshot,
    val strategyData: StrategyData,
    val homeSettings: JsonObject?,
)

private fun DashboardConfigResult.toUiState(
    urlPath: String?,
    inputs: StructureInputs,
    stack: List<String>,
): DashboardUiState = when (this) {
    is DashboardConfigResult.Error -> DashboardUiState.Error(message)
    // Without a stored default dashboard the frontend shows the generated home dashboard (/home)
    DashboardConfigResult.NotFound -> if (urlPath == null) {
        DashboardConfig(inputs.hass.homeDashboard(HomeDashboardConfig.fromSystemData(inputs.homeSettings)))
            .toContent(inputs, stack)
    } else {
        DashboardUiState.NotFound
    }
    is DashboardConfigResult.Loaded -> config.toContent(inputs, stack)
}

private fun DashboardConfig.toContent(inputs: StructureInputs, stack: List<String>): DashboardUiState {
    if (isStrategy) return DashboardUiState.UnsupportedStrategy(strategy?.string("type"))
    val views = views

    // A view is addressed by its path, or by its index when it has none (as frontend URLs do)
    fun pathOf(index: Int) = views[index].path ?: index.toString()
    fun indexOf(path: String) = views.indices.firstOrNull { pathOf(it) == path }

    // Drop paths a config change removed, falling back to the first view
    val shownIndex = stack.lastOrNull()?.let(::indexOf) ?: 0
    val shown = views.getOrNull(shownIndex)
    val tabIndices = views.indices.filter { !views[it].subview }
    val tabIndex = stack.mapNotNull(::indexOf).lastOrNull { it in tabIndices } ?: tabIndices.firstOrNull() ?: 0

    val expanded = shown?.let { inputs.hass.expandView(it, inputs.strategyData) }
    return DashboardUiState.Content(
        title = title,
        tabs = tabIndices.map { ViewTab(views[it].title, views[it].icon, pathOf(it)) },
        selectedTab = tabIndices.indexOf(tabIndex).coerceAtLeast(0),
        isSubview = shown?.subview == true,
        subviewTitle = shown?.title,
        viewPath = if (shown != null) pathOf(shownIndex) else "",
        maxColumns = shown?.json?.number("max_columns")?.toInt(),
        groups = expanded?.let(::cardGroups) ?: if (views.isEmpty()) emptyList() else null,
        view = expanded,
    )
}

private val STOP_TIMEOUT = 5.seconds.inWholeMilliseconds
private val CLOCK_TICK = 15.seconds

/** How often camera snapshots are refreshed (`UPDATE_INTERVAL` of src/panels/lovelace/components/hui-image.ts). */
private val CAMERA_REFRESH = 10.seconds

/** The language of the bundled frontend strings; server translations are fetched in the same language. */
private const val BUNDLED_LANGUAGE = "en"

private const val ACTION_ASSIST = "assist"
private const val ACTION_FIRE_DOM_EVENT = "fire-dom-event"

private fun CardAction.CallService.withCode(code: String) =
    copy(data = JsonObject(data.orEmpty() + ("code" to JsonPrimitive(code))), code = null)
