#!/usr/bin/env python3
"""Generate the frontend's own `mdi:` icons (logos it ships instead of, or on top of, MDI) for the native dashboard.

Usage: extract_custom_icons.py <frontend checkout>
Reads CUSTOM_ICONS in src/components/ha-icon.ts and the path of each icon from its src/resources module, and writes
dashboard/src/main/kotlin/.../ui/cards/FrontendCustomIcons.kt.
"""

import re
import sys
from pathlib import Path

OUT = (
    Path(__file__).resolve().parents[2]
    / "dashboard/src/main/kotlin/io/homeassistant/companion/android/dashboard/ui/cards/FrontendCustomIcons.kt"
)
# "music-assistant": () => import("../resources/music-assistant-logo-svg").then((mod) => mod.mdiMusicAssistant),
ENTRY = re.compile(
    r'"?([a-z0-9-]+)"?:\s*\(\)\s*=>\s*import\("\.\./resources/([a-z0-9-]+)"\)\s*\.then\(\s*\(mod\)\s*=>\s*mod\.(\w+)\s*\)',
)


def main(frontend: Path) -> None:
    source = (frontend / "src/components/ha-icon.ts").read_text()
    start = source.index("const CUSTOM_ICONS")
    block = source[start : source.index("};", start)]
    lines = []
    for name, module, export in ENTRY.findall(block):
        resource = (frontend / "src/resources" / f"{module}.ts").read_text()
        path = re.search(rf'export const {export}\s*=\s*"([^"]+)"', resource).group(1)
        lines.append(f'    "{name}" to "{path}",')
    if not lines:
        sys.exit("No custom icons found")
    OUT.write_text(
        "package io.homeassistant.companion.android.dashboard.ui.cards\n\n"
        "// Generated by tools/icons/extract_custom_icons.py from the frontend's\n"
        "// src/components/ha-icon.ts (CUSTOM_ICONS). Do not edit by hand.\n\n"
        "/** The `mdi:` icons the frontend draws itself instead of MDI's: icon name to its 24x24 SVG path. */\n"
        "internal val FRONTEND_CUSTOM_ICONS: Map<String, String> = mapOf(\n"
        + "\n".join(lines)
        + "\n)\n"
    )
    print(f"Wrote {len(lines)} icons to {OUT}")


if __name__ == "__main__":
    main(Path(sys.argv[1]))
