package io.homeassistant.companion.android.dashboard.model

import kotlinx.serialization.json.JsonObject

// Config wrappers around the raw JSON returned by `lovelace/config`. They never copy fields out:
// the wrapped JsonObject stays the single source of truth, so unknown and future keys are preserved
// and an unmodified config always round-trips exactly.
// Port of frontend@20260624.6 src/data/lovelace/config/{types,view,section,card}.ts

/** A dashboard config: either a list of views or a `strategy` to generate them. */
@JvmInline
value class DashboardConfig(val json: JsonObject) {
    /** Port of `isStrategyDashboard`: true when the dashboard must be generated by a strategy. */
    val isStrategy: Boolean get() = json.has(KEY_STRATEGY)
    val strategy: JsonObject? get() = json.obj(KEY_STRATEGY)
    val title: String? get() = json.string("title")
    val views: List<ViewConfig> get() = json.objects("views").map(::ViewConfig)
}

/** A dashboard view. */
@JvmInline
value class ViewConfig(val json: JsonObject) {
    /** Port of `isStrategyView`. */
    val isStrategy: Boolean get() = json.has(KEY_STRATEGY)
    val strategy: JsonObject? get() = json.obj(KEY_STRATEGY)
    val title: String? get() = json.string("title")
    val path: String? get() = json.string("path")
    val icon: String? get() = json.string("icon")
    val subview: Boolean get() = json.boolean("subview") == true
    val cards: List<CardConfig> get() = json.objects("cards").map(::CardConfig)
    val sections: List<SectionConfig> get() = json.objects("sections").map(::SectionConfig)
    val badges: List<JsonObject> get() = json.objects("badges")

    /**
     * The layout used to render this view.
     * Port of `getViewType` (src/panels/lovelace/views/get-view-type.ts).
     */
    val viewType: String
        get() = json.string("type")
            ?: when {
                json.boolean("panel") == true -> ViewType.PANEL
                json.has("sections") -> ViewType.SECTIONS
                json.has("cards") -> ViewType.MASONRY
                else -> ViewType.SECTIONS
            }
}

/** A section of a `sections` view. */
@JvmInline
value class SectionConfig(val json: JsonObject) {
    /** Port of `isStrategySection`. */
    val isStrategy: Boolean get() = json.has(KEY_STRATEGY)
    val type: String? get() = json.string("type")
    val cards: List<CardConfig> get() = json.objects("cards").map(::CardConfig)
    val visibility: List<JsonObject> get() = json.objects("visibility")
}

/** A card. The `type` decides which renderer applies; `custom:` types need the web frontend. */
@JvmInline
value class CardConfig(val json: JsonObject) {
    val type: String? get() = json.string("type")
    val isCustom: Boolean get() = type?.startsWith(CUSTOM_TYPE_PREFIX) == true
    val entity: String? get() = json.string("entity")
    val visibility: List<JsonObject> get() = json.objects("visibility")
}

/** View layout names, from src/panels/lovelace/views/const.ts. */
object ViewType {
    const val MASONRY = "masonry"
    const val PANEL = "panel"
    const val SIDEBAR = "sidebar"
    const val SECTIONS = "sections"
}

private const val KEY_STRATEGY = "strategy"
private const val CUSTOM_TYPE_PREFIX = "custom:"
