#!/usr/bin/env python3
"""Generate the frontend's default colour variables for the native dashboard.

Usage: extract_colors.py <frontend checkout>
Reads src/resources/theme/color/color.globals.ts (colorStyles and darkColorStyles) and writes
dashboard/src/main/kotlin/.../ui/theme/FrontendColors.kt with every `--*-color` variable whose value is a hex
colour or a reference to another variable.
"""

import re
import sys
from pathlib import Path

OUT = (
    Path(__file__).resolve().parents[2]
    / "dashboard/src/main/kotlin/io/homeassistant/companion/android/dashboard/ui/theme/FrontendColors.kt"
)
DECL = re.compile(r"--([a-z0-9-]+-color):\s*([^;]+);")
HEX = re.compile(r"^#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})$")
REF = re.compile(r"^var\(--([a-z0-9-]+)\)$")


def block(source: str, name: str) -> str:
    start = source.index(f"export const {name} = css`")
    return source[start : source.index("`;", start)]


def entries(css: str) -> list[str]:
    out = []
    for name, value in DECL.findall(css):
        value = value.strip()
        if m := HEX.match(value):
            digits = m.group(1)
            if len(digits) == 3:
                digits = "".join(c * 2 for c in digits)
            out.append(f'    "{name}" to FrontendColor.Hex(0xFF{digits.upper()}),')
        elif m := REF.match(value):
            out.append(f'    "{name}" to FrontendColor.Ref("{m.group(1)}"),')
    return out


def main() -> None:
    frontend = Path(sys.argv[1])
    source = (frontend / "src/resources/theme/color/color.globals.ts").read_text()
    light = entries(block(source, "colorStyles"))
    dark = entries(block(source, "darkColorStyles"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        f"""package io.homeassistant.companion.android.dashboard.ui.theme

// Generated by tools/theme/extract_colors.py from the frontend's
// src/resources/theme/color/color.globals.ts. Do not edit by hand.

/** A frontend colour variable's default: a colour, or another variable. */
internal sealed interface FrontendColor {{
    data class Hex(val argb: Long) : FrontendColor

    data class Ref(val variable: String) : FrontendColor
}}

/** `colorStyles`: the light theme defaults. */
internal val FRONTEND_LIGHT_COLORS: Map<String, FrontendColor> = mapOf(
{chr(10).join(light)}
)

/** `darkColorStyles`: what the dark theme overrides. */
internal val FRONTEND_DARK_COLORS: Map<String, FrontendColor> = mapOf(
{chr(10).join(dark)}
)
"""
    )
    print(f"wrote {OUT} ({len(light)} light, {len(dark)} dark)")


if __name__ == "__main__":
    main()
